# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/calderking/Documents/GitHub/module-volumetric-models-team-c/voxel_view/qbvoxel/CMakeLists.txt))

/Users/calderking/Documents/GitHub/module-volumetric-models-team-c/voxel_view/buildck/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Applications/CMake.app/Contents/bin/cmake -H/Users/calderking/Documents/GitHub/module-volumetric-models-team-c/voxel_view -B/Users/calderking/Documents/GitHub/module-volumetric-models-team-c/voxel_view/buildck
